import type { VocabCardState, VocabTerm } from "@/types/vocab";
import { createRandom, shuffle } from "@/lib/scoring/selection";
import { normalizeAnswer } from "./matching";

/**
 * Study item generation.
 *
 * Every mode is a projection over the same term list, which is what keeps the
 * modes consistent with one another: the multiple-choice item a student sees
 * in Learn is generated by the same function that builds the one in Test, so
 * the distractors are equally plausible in both.
 *
 * Generation is seeded throughout. A resumed round rebuilds identically rather
 * than quietly reshuffling under the student, and tests can assert on exact
 * output.
 */

export type VocabDirection = "term-to-definition" | "definition-to-term";

export type VocabChoice = {
  id: string;
  text: string;
  termId: string;
};

export type VocabMultipleChoiceItem = {
  kind: "multiple-choice";
  termId: string;
  direction: VocabDirection;
  /** What the student is asked about. */
  prompt: string;
  /** The instruction above the prompt. */
  promptLabel: string;
  choices: VocabChoice[];
  correctChoiceId: string;
};

export type VocabWrittenItem = {
  kind: "written";
  termId: string;
  prompt: string;
  promptLabel: string;
  /** The canonical answer; aliases are accepted by the grader. */
  answer: string;
};

export type VocabTrueFalseItem = {
  kind: "true-false";
  termId: string;
  /** The pairing being asserted. */
  term: string;
  definition: string;
  correct: boolean;
  /** When false, the term the shown definition actually belongs to. */
  impostorTermId?: string;
};

export type VocabStudyItem =
  | VocabMultipleChoiceItem
  | VocabWrittenItem
  | VocabTrueFalseItem;

const DEFAULT_OPTION_COUNT = 4;

function promptFor(term: VocabTerm, direction: VocabDirection): string {
  return direction === "term-to-definition" ? term.term : term.definition;
}

function answerFor(term: VocabTerm, direction: VocabDirection): string {
  return direction === "term-to-definition" ? term.definition : term.term;
}

function labelFor(direction: VocabDirection): string {
  return direction === "term-to-definition"
    ? "What does this term mean?"
    : "Which term is being described?";
}

/**
 * Picks distractors for one item.
 *
 * Preference order is the whole point: a term's declared confusables are the
 * mistakes students actually make, so they are offered first. Same-category
 * terms come next, and only then anything else. Options are de-duplicated by
 * *normalized answer text* rather than by term, because two options that read
 * the same make a question unanswerable.
 */
export function pickDistractors(
  term: VocabTerm,
  pool: VocabTerm[],
  direction: VocabDirection,
  count: number,
  seed: number,
): VocabTerm[] {
  const byId = new Map(pool.map((candidate) => [candidate.id, candidate]));
  const random = createRandom(seed);

  const confusable = (term.confusableWithIds ?? [])
    .map((id) => byId.get(id))
    .filter((candidate): candidate is VocabTerm => candidate !== undefined);

  const related = (term.relatedTermIds ?? [])
    .map((id) => byId.get(id))
    .filter((candidate): candidate is VocabTerm => candidate !== undefined);

  const sameCategory = shuffle(
    pool.filter(
      (candidate) =>
        candidate.id !== term.id && candidate.category === term.category,
    ),
    random,
  );

  const anywhere = shuffle(
    pool.filter((candidate) => candidate.id !== term.id),
    random,
  );

  const used = new Set([normalizeAnswer(answerFor(term, direction))]);
  const chosen: VocabTerm[] = [];

  for (const candidate of [...confusable, ...related, ...sameCategory, ...anywhere]) {
    if (chosen.length >= count) break;
    if (candidate.id === term.id) continue;
    const text = normalizeAnswer(answerFor(candidate, direction));
    if (text.length === 0 || used.has(text)) continue;
    used.add(text);
    chosen.push(candidate);
  }

  return chosen;
}

export function buildMultipleChoiceItem(
  term: VocabTerm,
  pool: VocabTerm[],
  direction: VocabDirection,
  seed: number,
  optionCount: number = DEFAULT_OPTION_COUNT,
): VocabMultipleChoiceItem {
  const distractors = pickDistractors(
    term,
    pool,
    direction,
    optionCount - 1,
    seed,
  );

  const choices = shuffle([term, ...distractors], createRandom(seed + 977)).map(
    (option, index) => ({
      id: `c${index}`,
      text: answerFor(option, direction),
      termId: option.id,
    }),
  );

  const correct = choices.find((choice) => choice.termId === term.id);

  return {
    kind: "multiple-choice",
    termId: term.id,
    direction,
    prompt: promptFor(term, direction),
    promptLabel: labelFor(direction),
    choices,
    correctChoiceId: correct?.id ?? "c0",
  };
}

export function buildWrittenItem(term: VocabTerm): VocabWrittenItem {
  return {
    kind: "written",
    termId: term.id,
    prompt: term.definition,
    promptLabel: "Type the term being described",
    answer: term.term,
  };
}

/**
 * A true/false item.
 *
 * False statements borrow a confusable term's definition rather than a random
 * one — a pairing that is obviously absurd tests nothing.
 */
export function buildTrueFalseItem(
  term: VocabTerm,
  pool: VocabTerm[],
  seed: number,
): VocabTrueFalseItem {
  const random = createRandom(seed);
  const shouldBeTrue = random() < 0.5;

  if (shouldBeTrue) {
    return {
      kind: "true-false",
      termId: term.id,
      term: term.term,
      definition: term.definition,
      correct: true,
    };
  }

  const impostor = pickDistractors(
    term,
    pool,
    "term-to-definition",
    1,
    seed + 31,
  )[0];

  if (!impostor) {
    return {
      kind: "true-false",
      termId: term.id,
      term: term.term,
      definition: term.definition,
      correct: true,
    };
  }

  return {
    kind: "true-false",
    termId: term.id,
    term: term.term,
    definition: impostor.definition,
    correct: false,
    impostorTermId: impostor.id,
  };
}

/**
 * How well a term is known, used to decide which item type it deserves.
 *
 * Recognition (multiple choice) is easier than recall (typing it). Promoting a
 * term from one to the other once the student has got it right twice is what
 * makes Learn mode feel like it is tracking them rather than looping.
 */
export function shouldPromoteToWritten(card: VocabCardState | undefined): boolean {
  if (!card) return false;
  return card.streak >= 2;
}

export type LearnQueueOptions = {
  pool: VocabTerm[];
  cards: Record<string, VocabCardState>;
  seed: number;
  /** Force every item to one type, for students who prefer it. */
  itemType?: "adaptive" | "multiple-choice" | "written";
  direction?: VocabDirection;
};

/**
 * Builds the item for each term in a queue.
 *
 * The queue order comes from the scheduler; this only decides *how* each term
 * is asked.
 */
export function buildLearnItems(
  queue: VocabTerm[],
  options: LearnQueueOptions,
): VocabStudyItem[] {
  const {
    pool,
    cards,
    seed,
    itemType = "adaptive",
    direction = "definition-to-term",
  } = options;

  return queue.map((term, index) => {
    const itemSeed = seed + index * 101;

    if (itemType === "written") {
      return buildWrittenItem(term);
    }
    if (itemType === "multiple-choice") {
      return buildMultipleChoiceItem(term, pool, direction, itemSeed);
    }

    return shouldPromoteToWritten(cards[term.id])
      ? buildWrittenItem(term)
      : buildMultipleChoiceItem(term, pool, direction, itemSeed);
  });
}

export type TestPaperOptions = {
  pool: VocabTerm[];
  seed: number;
  /** Which item types to include. At least one must be enabled. */
  include?: {
    multipleChoice?: boolean;
    written?: boolean;
    trueFalse?: boolean;
  };
};

/**
 * Builds a mixed test.
 *
 * Item types are dealt round-robin across the enabled kinds rather than picked
 * at random per question, so a ten-question test never lands on ten written
 * items by chance.
 */
export function buildTestPaper(
  terms: VocabTerm[],
  options: TestPaperOptions,
): VocabStudyItem[] {
  const { pool, seed, include } = options;
  const enabled: ("multiple-choice" | "written" | "true-false")[] = [];
  if (include?.multipleChoice ?? true) enabled.push("multiple-choice");
  if (include?.written ?? true) enabled.push("written");
  if (include?.trueFalse ?? true) enabled.push("true-false");

  const kinds = enabled.length > 0 ? enabled : ["multiple-choice" as const];
  const ordered = shuffle(terms, createRandom(seed));

  return ordered.map((term, index) => {
    const kind = kinds[index % kinds.length];
    const itemSeed = seed + index * 211;

    if (kind === "written") {
      return buildWrittenItem(term);
    }
    if (kind === "true-false") {
      return buildTrueFalseItem(term, pool, itemSeed);
    }
    return buildMultipleChoiceItem(
      term,
      pool,
      index % 2 === 0 ? "definition-to-term" : "term-to-definition",
      itemSeed,
    );
  });
}

export type MatchTile = {
  id: string;
  termId: string;
  face: "term" | "definition";
  text: string;
};

/**
 * Builds the board for Match.
 *
 * Definitions are truncated for the tile because a match board is a spatial
 * task — a tile carrying four lines of text turns it into a reading task and
 * the game stops being fun.
 */
export function buildMatchBoard(
  terms: VocabTerm[],
  seed: number,
  pairCount = 6,
): { tiles: MatchTile[]; pairs: VocabTerm[] } {
  const random = createRandom(seed);
  const pairs = shuffle(terms, random).slice(0, pairCount);

  const tiles: MatchTile[] = pairs.flatMap((term) => [
    {
      id: `${term.id}:term`,
      termId: term.id,
      face: "term" as const,
      text: term.term,
    },
    {
      id: `${term.id}:definition`,
      termId: term.id,
      face: "definition" as const,
      text: term.definition,
    },
  ]);

  return { tiles: shuffle(tiles, createRandom(seed + 1)), pairs };
}
